"""Shared validation and atomic publication for generated slide images."""

import base64
import binascii
import http.client
import os
import stat
import tempfile
from pathlib import Path

from PIL import Image, UnidentifiedImageError

OUTPUT_FORMATS = {
    ".jpg": "jpeg",
    ".jpeg": "jpeg",
    ".png": "png",
    ".webp": "webp",
}
PIL_FORMATS = {
    "jpeg": "JPEG",
    "png": "PNG",
    "webp": "WEBP",
}
MIME_TYPES = {
    "jpeg": "image/jpeg",
    "png": "image/png",
    "webp": "image/webp",
}


class ImageOutputError(ValueError):
    """Raised when generated bytes cannot safely become the requested output."""


class ImageStreamError(ImageOutputError):
    """Raised for a retryable transport failure while reading image bytes."""


def validate_retries(retries: object) -> int:
    if isinstance(retries, bool) or not isinstance(retries, int) or retries < 0:
        raise ImageOutputError("retries must be a non-boolean integer >= 0")
    return retries


def output_format(out_path: str) -> str:
    extension = Path(out_path).suffix.lower()
    try:
        return OUTPUT_FORMATS[extension]
    except KeyError as error:
        supported = ", ".join(sorted(OUTPUT_FORMATS))
        raise ImageOutputError(
            f"Unsupported output extension '{extension or '<none>'}'. Use: {supported}"
        ) from error


def expected_mime_type(out_path: str) -> str:
    return MIME_TYPES[output_format(out_path)]


def decode_base64(encoded: object) -> bytes:
    if not isinstance(encoded, str) or not encoded:
        raise ImageOutputError("image Base64 must be a non-empty string")
    try:
        decoded = base64.b64decode(encoded, validate=True)
    except (binascii.Error, UnicodeError, ValueError) as error:
        raise ImageOutputError("image Base64 is invalid") from error
    if not decoded:
        raise ImageOutputError("image data is empty")
    return decoded


def preflight_output(out_path: str, overwrite: bool = False) -> Path:
    if not isinstance(overwrite, bool):
        raise ImageOutputError("overwrite must be a boolean")

    target = Path(out_path)
    try:
        target.parent.mkdir(parents=True, exist_ok=True)
        if os.path.lexists(target):
            if not overwrite:
                raise ImageOutputError(
                    f"output already exists; refusing to overwrite: {target}"
                )
            mode = target.lstat().st_mode
            if not stat.S_ISREG(mode):
                raise ImageOutputError(
                    "output path exists and is not a regular file"
                )
        descriptor, probe_path = tempfile.mkstemp(
            prefix=".write-test.", dir=str(target.parent)
        )
        os.close(descriptor)
        os.unlink(probe_path)
    except ImageOutputError:
        raise
    except (OSError, ValueError) as error:
        raise ImageOutputError(f"output path is not writable: {error}") from error
    return target


def _temporary_path(target: Path):
    try:
        return tempfile.mkstemp(
            prefix=f".{target.name}.", suffix=".tmp", dir=str(target.parent)
        )
    except OSError as error:
        raise ImageOutputError(f"failed to create output temporary file: {error}") from error


def _remove_temp(path: str) -> None:
    try:
        os.unlink(path)
    except FileNotFoundError:
        pass
    except OSError as error:
        raise ImageOutputError(f"failed to remove output temporary file: {error}") from error


def _validate_temp(path: str, target: Path) -> int:
    try:
        byte_count = os.path.getsize(path)
        if byte_count <= 0:
            raise ImageOutputError("image data is empty")
        with Image.open(path) as image:
            image.verify()
        with Image.open(path) as image:
            image.load()
            width, height = image.size
            actual_format = image.format
    except ImageOutputError:
        raise
    except (OSError, ValueError, UnidentifiedImageError) as error:
        raise ImageOutputError(f"generated data is not a valid image: {error}") from error

    expected_format = PIL_FORMATS[output_format(str(target))]
    if actual_format != expected_format:
        raise ImageOutputError(
            f"image format {actual_format or '<unknown>'} does not match "
            f"{target.suffix.lower()}"
        )
    if width <= 0 or height <= 0 or width * 9 != height * 16:
        raise ImageOutputError(
            f"generated image must be exactly 16:9; received {width}x{height}"
        )
    return byte_count


def _publish_temp(temp_path: str, target: Path, overwrite: bool) -> None:
    try:
        if overwrite:
            os.replace(temp_path, target)
        else:
            os.link(temp_path, target)
            os.unlink(temp_path)
    except FileExistsError as error:
        raise ImageOutputError(
            f"output already exists; refusing to overwrite: {target}"
        ) from error
    except OSError as error:
        raise ImageOutputError(f"failed to publish image atomically: {error}") from error


def publish_bytes(data: bytes, target: Path, overwrite: bool = False) -> int:
    if not isinstance(data, bytes) or not data:
        raise ImageOutputError("image data must be non-empty bytes")
    descriptor, temp_path = _temporary_path(target)
    published = False
    try:
        with os.fdopen(descriptor, "wb") as output:
            output.write(data)
            output.flush()
            os.fsync(output.fileno())
        byte_count = _validate_temp(temp_path, target)
        _publish_temp(temp_path, target, overwrite)
        published = True
        return byte_count
    except ImageOutputError:
        raise
    except OSError as error:
        raise ImageOutputError(f"failed to write image: {error}") from error
    finally:
        if not published and os.path.lexists(temp_path):
            _remove_temp(temp_path)


def publish_stream(
    response,
    target: Path,
    overwrite: bool = False,
    max_bytes: int = 50 * 1024 * 1024,
) -> int:
    headers = getattr(response, "headers", {})
    content_length = None
    try:
        content_length = headers.get("Content-Length")
    except AttributeError:
        pass
    if content_length:
        try:
            declared_length = int(content_length)
        except (TypeError, ValueError) as error:
            raise ImageOutputError("download Content-Length is invalid") from error
        if declared_length < 0 or declared_length > max_bytes:
            raise ImageOutputError(
                f"download exceeds maximum image size of {max_bytes} bytes"
            )

    descriptor, temp_path = _temporary_path(target)
    published = False
    try:
        byte_count = 0
        with os.fdopen(descriptor, "wb") as output:
            while True:
                try:
                    chunk = response.read(64 * 1024)
                except (OSError, http.client.HTTPException) as error:
                    raise ImageStreamError(f"image download failed: {error}") from error
                if not chunk:
                    break
                if not isinstance(chunk, bytes):
                    raise ImageOutputError("download returned non-byte image data")
                byte_count += len(chunk)
                if byte_count > max_bytes:
                    raise ImageOutputError(
                        f"download exceeds maximum image size of {max_bytes} bytes"
                    )
                output.write(chunk)
            output.flush()
            os.fsync(output.fileno())
        byte_count = _validate_temp(temp_path, target)
        _publish_temp(temp_path, target, overwrite)
        published = True
        return byte_count
    except ImageOutputError:
        raise
    except OSError as error:
        raise ImageOutputError(f"failed to download image: {error}") from error
    finally:
        if not published and os.path.lexists(temp_path):
            _remove_temp(temp_path)
