"""Shared validation and atomic publication for generated slide images."""

import base64
import binascii
import http.client
import io
import json
import os
import secrets
import stat
import sys
import tempfile
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import NamedTuple, Optional, Union

from PIL import Image, UnidentifiedImageError

OUTPUT_FORMATS = {
    ".jpg": "jpeg",
    ".jpeg": "jpeg",
    ".png": "png",
    ".webp": "webp",
}
PIL_FORMATS = {
    "jpeg": "JPEG",
    "png": "PNG",
    "webp": "WEBP",
}
MIME_TYPES = {
    "jpeg": "image/jpeg",
    "png": "image/png",
    "webp": "image/webp",
}
MAX_IMAGE_BYTES = 50 * 1024 * 1024
MAX_IMAGE_PIXELS = 64_000_000
MAX_ENCODED_IMAGE_BYTES = 4 * ((MAX_IMAGE_BYTES + 2) // 3)
MAX_PROVIDER_RESPONSE_BYTES = MAX_ENCODED_IMAGE_BYTES + 1024 * 1024
PROVIDER_RESPONSE_READ_CHUNK_BYTES = 64 * 1024
MAX_PROVIDER_RESPONSE_READS = 4096
IMAGE_STREAM_READ_CHUNK_BYTES = 64 * 1024
MAX_RETRIES = 10
MAX_JSON_NESTING = 100
MAX_JSON_NODES = 100_000
MAX_JSON_CONTAINER_ITEMS = 10_000


class ImageOutputError(ValueError):
    """Raised when generated bytes cannot safely become the requested output."""


class ImageStreamError(ImageOutputError):
    """Raised for a retryable transport failure while reading image bytes."""


class LoadedImage(NamedTuple):
    image: Optional[Image.Image]
    image_format: str
    byte_count: int
    width: int
    height: int


@dataclass(frozen=True)
class ParentIdentity:
    path: Path
    real_path: Path
    device: int
    inode: int


@dataclass(frozen=True)
class PreparedTarget:
    path: Path
    parent: ParentIdentity

    def __fspath__(self) -> str:
        return str(self.path)

    def __str__(self) -> str:
        return str(self.path)

    @property
    def suffix(self) -> str:
        return self.path.suffix

    @property
    def name(self) -> str:
        return self.path.name


@dataclass(frozen=True)
class TemporaryOutput:
    descriptor: int
    parent_fd: int
    name: str
    device: int
    inode: int
    parent: ParentIdentity

    def __fspath__(self) -> str:
        return str(self.parent.path / self.name)

    def __str__(self) -> str:
        return os.fspath(self)


TargetValue = Union[Path, PreparedTarget]


def validate_retries(retries: object) -> int:
    if (
        isinstance(retries, bool)
        or not isinstance(retries, int)
        or retries < 0
        or retries > MAX_RETRIES
    ):
        raise ImageOutputError(
            f"retries must be a non-boolean integer >= 0 and at most {MAX_RETRIES}"
        )
    return retries


def _scan_json_structure(raw_response: object) -> None:
    """Bound JSON structure before the standard decoder allocates containers."""
    if not isinstance(raw_response, (str, bytes, bytearray)):
        raise ValueError("JSON input must be text or bytes")

    is_bytes = not isinstance(raw_response, str)
    if is_bytes:
        if raw_response.startswith((b"\xff\xfe", b"\xfe\xff", b"\x00\x00\xfe\xff", b"\xff\xfe\x00\x00")):
            raise ValueError("provider JSON must use UTF-8")
        index = 3 if raw_response.startswith(b"\xef\xbb\xbf") else 0
        quote, slash = 34, 92
        left_array, right_array = 91, 93
        left_object, right_object = 123, 125
        comma, colon = 44, 58
        whitespace = (9, 10, 13, 32)
    else:
        index = 0
        quote, slash = '"', "\\"
        left_array, right_array = "[", "]"
        left_object, right_object = "{", "}"
        comma, colon = ",", ":"
        whitespace = ("\t", "\n", "\r", " ")

    length = len(raw_response)
    stack = []
    root_state = "value"
    node_count = 0

    def skip_string(position: int) -> int:
        position += 1
        while position < length:
            current = raw_response[position]
            if current == slash:
                position += 2
                continue
            if current == quote:
                return position + 1
            position += 1
        raise ValueError("unterminated JSON string")

    def consume_value(position: int) -> int:
        nonlocal node_count, root_state
        if stack:
            context = stack[-1]
            if context[0] == "array":
                context[2] += 1
                if context[2] > MAX_JSON_CONTAINER_ITEMS:
                    raise ValueError("JSON container has too many items")
                context[1] = "comma_or_end"
            else:
                context[1] = "comma_or_end"
        else:
            root_state = "end"

        node_count += 1
        if node_count > MAX_JSON_NODES:
            raise ValueError("JSON has too many nodes")

        current = raw_response[position]
        if current == quote:
            return skip_string(position)
        if current in (left_array, left_object):
            if len(stack) > MAX_JSON_NESTING:
                raise ValueError("JSON nesting is too deep")
            if current == left_array:
                stack.append(["array", "value_or_end", 0])
            else:
                stack.append(["object", "key_or_end", 0])
            return position + 1

        start = position
        while position < length:
            current = raw_response[position]
            if current in whitespace or current in (comma, right_array, right_object):
                break
            position += 1
        if position == start:
            raise ValueError("expected JSON value")
        return position

    while True:
        while index < length and raw_response[index] in whitespace:
            index += 1

        if not stack:
            if root_state == "end":
                if index != length:
                    raise ValueError("trailing JSON data")
                return
            if index == length:
                raise ValueError("empty JSON input")
            index = consume_value(index)
            continue

        context = stack[-1]
        kind, state = context[0], context[1]
        if index == length:
            raise ValueError("incomplete JSON container")
        current = raw_response[index]

        if kind == "array":
            if state == "value_or_end" and current == right_array:
                stack.pop()
                index += 1
            elif state in ("value_or_end", "value"):
                index = consume_value(index)
            elif state == "comma_or_end" and current == comma:
                context[1] = "value"
                index += 1
            elif state == "comma_or_end" and current == right_array:
                stack.pop()
                index += 1
            else:
                raise ValueError("invalid JSON array structure")
            continue

        if state in ("key_or_end", "key"):
            if state == "key_or_end" and current == right_object:
                stack.pop()
                index += 1
            elif current == quote:
                context[2] += 1
                if context[2] > MAX_JSON_CONTAINER_ITEMS:
                    raise ValueError("JSON container has too many items")
                index = skip_string(index)
                context[1] = "colon"
            else:
                raise ValueError("invalid JSON object key")
        elif state == "colon" and current == colon:
            context[1] = "value"
            index += 1
        elif state == "value":
            index = consume_value(index)
        elif state == "comma_or_end" and current == comma:
            context[1] = "key"
            index += 1
        elif state == "comma_or_end" and current == right_object:
            stack.pop()
            index += 1
        else:
            raise ValueError("invalid JSON object structure")


def _object_without_duplicate_keys(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON object key")
        result[key] = value
    return result


def parse_json_response(raw_response: object) -> object:
    """Parse bounded provider JSON without leaking decoder recursion failures."""
    try:
        _scan_json_structure(raw_response)
        parsed = json.loads(
            raw_response,
            object_pairs_hook=_object_without_duplicate_keys,
        )
    except (TypeError, ValueError, UnicodeError, RecursionError) as error:
        raise ImageOutputError("provider response is not valid JSON") from error

    # CPython's JSON decoder recursion behavior differs by version. Enforce
    # deterministic resource limits with one iterator frame per active level;
    # never allocate one pending traversal tuple per sibling.
    stack = []
    value = parsed
    depth = 0
    node_count = 0
    while True:
        node_count += 1
        if node_count > MAX_JSON_NODES:
            raise ImageOutputError("provider response is not valid JSON")

        if isinstance(value, (dict, list)):
            if depth > MAX_JSON_NESTING or len(value) > MAX_JSON_CONTAINER_ITEMS:
                raise ImageOutputError("provider response is not valid JSON")
            children = value.values() if isinstance(value, dict) else value
            stack.append((iter(children), depth + 1))

        while stack:
            children, child_depth = stack[-1]
            try:
                value = next(children)
            except StopIteration:
                stack.pop()
                continue
            depth = child_depth
            break
        else:
            return parsed


def output_format(out_path: str) -> str:
    extension = Path(out_path).suffix.lower()
    try:
        return OUTPUT_FORMATS[extension]
    except KeyError as error:
        supported = ", ".join(sorted(OUTPUT_FORMATS))
        raise ImageOutputError(
            f"Unsupported output extension '{extension or '<none>'}'. Use: {supported}"
        ) from error


def expected_mime_type(out_path: str) -> str:
    return MIME_TYPES[output_format(out_path)]


def capture_path_base() -> Path:
    """Capture one absolute CWD for resolving every path in a public call."""
    try:
        return Path.cwd()
    except (OSError, ValueError, RuntimeError) as error:
        raise ImageOutputError(
            f"cannot capture current working directory: {error}"
        ) from error


def _absolute_path(value: object, base: Optional[Path]) -> Path:
    expanded = Path(value).expanduser()
    path_base = capture_path_base() if base is None else Path(base)
    if not path_base.is_absolute():
        raise ValueError("path base must be absolute")
    combined = expanded if expanded.is_absolute() else path_base / expanded
    absolute = Path(os.path.abspath(str(combined)))
    if "\0" in str(absolute):
        raise ValueError("embedded null byte")
    return absolute


def resolve_output_path(target: object, base: Optional[Path] = None) -> Path:
    """Freeze output ancestors as a real absolute path without following basename."""
    try:
        absolute = _absolute_path(target, base)
        return absolute.parent.resolve(strict=False) / absolute.name
    except (TypeError, ValueError, OSError, RuntimeError) as error:
        raise ImageOutputError(f"invalid output target: {error}") from error


def resolve_input_path(source: object, base: Optional[Path] = None) -> Path:
    """Freeze an input path, following its current final symlink referent."""
    try:
        return _absolute_path(source, base).resolve(strict=False)
    except (TypeError, ValueError, OSError, RuntimeError) as error:
        raise ImageOutputError(f"invalid input path: {error}") from error


def decode_base64(encoded: object) -> bytes:
    if not isinstance(encoded, str) or not encoded:
        raise ImageOutputError("image Base64 must be a non-empty string")
    max_encoded_bytes = 4 * ((MAX_IMAGE_BYTES + 2) // 3)
    if len(encoded) > max_encoded_bytes:
        raise ImageOutputError(
            f"image Base64 exceeds maximum encoded size of {max_encoded_bytes} bytes"
        )
    try:
        decoded = base64.b64decode(encoded, validate=True)
    except (binascii.Error, UnicodeError, ValueError) as error:
        raise ImageOutputError("image Base64 is invalid") from error
    if not decoded:
        raise ImageOutputError("image data is empty")
    if len(decoded) > MAX_IMAGE_BYTES:
        raise ImageOutputError(
            f"image data exceeds maximum size of {MAX_IMAGE_BYTES} bytes"
        )
    return decoded


def read_response_body(response) -> bytes:
    """Read one provider response with a hard maximum allocation boundary."""
    data = bytearray()
    remaining = MAX_PROVIDER_RESPONSE_BYTES + 1
    read_count = 0
    while remaining:
        if read_count >= MAX_PROVIDER_RESPONSE_READS:
            raise ImageOutputError("provider response returned too many chunks")
        read_count += 1
        try:
            chunk = response.read(
                min(PROVIDER_RESPONSE_READ_CHUNK_BYTES, remaining)
            )
        except TypeError as error:
            raise ImageOutputError(
                "provider response does not support bounded reads"
            ) from error
        except (OSError, http.client.HTTPException) as error:
            raise ImageStreamError(
                f"provider response read failed: {error}"
            ) from error
        if not isinstance(chunk, bytes):
            raise ImageOutputError("provider response body must be bytes")
        if not chunk:
            break
        data.extend(chunk[:remaining])
        remaining -= min(len(chunk), remaining)

    if len(data) > MAX_PROVIDER_RESPONSE_BYTES:
        raise ImageOutputError(
            "provider response exceeds maximum size of "
            f"{MAX_PROVIDER_RESPONSE_BYTES} bytes"
        )
    return bytes(data)


def read_bounded_image_stream(stream, max_bytes: int = MAX_IMAGE_BYTES) -> bytes:
    """Read image bytes without allowing an unbounded stream allocation."""
    if isinstance(max_bytes, bool) or not isinstance(max_bytes, int) or max_bytes <= 0:
        raise ImageOutputError("maximum image size must be a positive integer")

    headers = getattr(stream, "headers", {})
    try:
        content_length = headers.get("Content-Length")
    except AttributeError:
        content_length = None
    if content_length:
        try:
            declared_length = int(content_length)
        except (TypeError, ValueError) as error:
            raise ImageOutputError("download Content-Length is invalid") from error
        if declared_length < 0 or declared_length > max_bytes:
            raise ImageOutputError(
                f"download exceeds maximum image size of {max_bytes} bytes"
            )

    data = bytearray()
    max_reads = min(
        MAX_PROVIDER_RESPONSE_READS,
        (max_bytes + IMAGE_STREAM_READ_CHUNK_BYTES - 1)
        // IMAGE_STREAM_READ_CHUNK_BYTES + 1,
    )
    for _read_count in range(max_reads):
        remaining = max_bytes - len(data)
        try:
            chunk = stream.read(min(IMAGE_STREAM_READ_CHUNK_BYTES, remaining + 1))
        except TypeError as error:
            raise ImageOutputError("image stream does not support bounded reads") from error
        except (OSError, http.client.HTTPException) as error:
            raise ImageStreamError(f"image stream read failed: {error}") from error
        if not isinstance(chunk, bytes):
            raise ImageOutputError("image stream returned non-byte data")
        if not chunk:
            return bytes(data)
        data.extend(chunk)
        if len(data) > max_bytes:
            raise ImageOutputError(
                f"image data exceeds maximum size of {max_bytes} bytes"
            )
    raise ImageOutputError("image stream returned too many chunks")


def _validate_dimensions(width: int, height: int) -> None:
    if width <= 0 or height <= 0:
        raise ImageOutputError("image dimensions must be positive")
    if width * height > MAX_IMAGE_PIXELS:
        raise ImageOutputError(
            "image dimensions are too large; maximum pixel count is "
            f"{MAX_IMAGE_PIXELS}"
        )


def _load_image_data(
    data: bytes,
    verify: bool = False,
    copy_image: bool = True,
) -> LoadedImage:
    """Load one image under shared byte, pixel, and Pillow bomb limits."""
    try:
        if not isinstance(data, bytes) or not data:
            raise ImageOutputError("image data is empty")
        if len(data) > MAX_IMAGE_BYTES:
            raise ImageOutputError(
                f"image data exceeds maximum size of {MAX_IMAGE_BYTES} bytes"
            )
        byte_count = len(data)

        with warnings.catch_warnings():
            warnings.simplefilter("error", Image.DecompressionBombWarning)
            if verify:
                with Image.open(io.BytesIO(data)) as image:
                    _validate_dimensions(*image.size)
                    image.verify()
            with Image.open(io.BytesIO(data)) as image:
                width, height = image.size
                _validate_dimensions(width, height)
                image_format = image.format
                image.load()
                loaded = image.copy() if copy_image else None
    except ImageOutputError:
        raise
    except (Image.DecompressionBombError, Image.DecompressionBombWarning) as error:
        raise ImageOutputError(f"image dimensions are too large: {error}") from error
    except (OSError, SyntaxError, ValueError, UnidentifiedImageError) as error:
        raise ImageOutputError(f"data is not a valid image: {error}") from error

    return LoadedImage(loaded, image_format, byte_count, width, height)


def load_image(
    path: Path,
    verify: bool = False,
    copy_image: bool = True,
) -> LoadedImage:
    """Load one image under shared byte, pixel, and Pillow bomb limits."""
    image_path = Path(path)
    try:
        stated_size = image_path.stat().st_size
        if stated_size <= 0:
            raise ImageOutputError("image data is empty")
        if stated_size > MAX_IMAGE_BYTES:
            raise ImageOutputError(
                f"image exceeds maximum size of {MAX_IMAGE_BYTES} bytes"
            )
        with image_path.open("rb") as source:
            data = source.read(MAX_IMAGE_BYTES + 1)
        if len(data) > MAX_IMAGE_BYTES:
            raise ImageOutputError(
                f"image exceeds maximum size of {MAX_IMAGE_BYTES} bytes"
            )
    except ImageOutputError:
        raise
    except (OSError, ValueError) as error:
        raise ImageOutputError(f"data is not a valid image: {error}") from error
    return _load_image_data(data, verify=verify, copy_image=copy_image)


def validate_decoded_image_bytes(
    data: bytes,
    target: object,
    copy_image: bool = False,
) -> LoadedImage:
    """Validate bounded, decodable image bytes and the requested file format."""
    if not isinstance(data, bytes) or not data:
        raise ImageOutputError("image data must be non-empty bytes")
    if len(data) > MAX_IMAGE_BYTES:
        raise ImageOutputError(
            f"image data exceeds maximum size of {MAX_IMAGE_BYTES} bytes"
        )
    loaded = _load_image_data(data, verify=True, copy_image=copy_image)
    expected = PIL_FORMATS[output_format(str(target))]
    if loaded.image_format != expected:
        raise ImageOutputError(
            f"image format {loaded.image_format or '<unknown>'} does not match "
            f"{Path(str(target)).suffix.lower()}"
        )
    return loaded


def validate_image_bytes(data: bytes, target: object) -> LoadedImage:
    """Validate a provider output, including the strict 16:9 public boundary."""
    loaded = validate_decoded_image_bytes(data, target)
    if loaded.width * 9 != loaded.height * 16:
        raise ImageOutputError(
            f"generated image must be exactly 16:9; received "
            f"{loaded.width}x{loaded.height}"
        )
    return loaded


def prepare_target(target: Path) -> PreparedTarget:
    """Capture the parent directory identity for one output target."""
    try:
        output_path = Path(os.path.abspath(str(Path(target).expanduser())))
    except (TypeError, ValueError, OSError) as error:
        raise ImageOutputError(f"invalid output target: {error}") from error
    parent_path = output_path.parent
    try:
        parent_path.mkdir(parents=True, exist_ok=True)
        if parent_path.is_symlink():
            raise ImageOutputError(
                f"parent directory identity is unsafe: {parent_path} is a symlink"
            )
        real_path = parent_path.resolve(strict=True)
        parent_stat = parent_path.stat()
        if not stat.S_ISDIR(parent_stat.st_mode):
            raise ImageOutputError(
                f"parent directory identity is unsafe: {parent_path} is not a directory"
            )
    except ImageOutputError:
        raise
    except (OSError, ValueError) as error:
        raise ImageOutputError(
            f"cannot capture parent directory identity: {error}"
        ) from error
    return PreparedTarget(
        output_path,
        ParentIdentity(
            parent_path,
            real_path,
            parent_stat.st_dev,
            parent_stat.st_ino,
        ),
    )


def prepare_workspace_target(target: object, workspace_root: object) -> PreparedTarget:
    """Capture a writable output target that cannot leave a workspace root."""
    try:
        root = Path(workspace_root).expanduser().resolve(strict=True)
        if not root.is_dir():
            raise ImageOutputError("workspace root must be an existing directory")
        raw = Path(target).expanduser()
        if ".." in raw.parts:
            raise ImageOutputError("output target must not traverse outside workspace")
        absolute = raw if raw.is_absolute() else root / raw
        resolved = resolve_output_path(absolute, base=root)
        if resolved.parent != root and root not in resolved.parent.parents:
            raise ImageOutputError("output target escapes workspace root")
        prepared = prepare_target(resolved)
        if (
            prepared.parent.real_path != root
            and root not in prepared.parent.real_path.parents
        ):
            raise ImageOutputError("resolved output parent escapes workspace root")
        return prepared
    except ImageOutputError:
        raise
    except (OSError, TypeError, ValueError, RuntimeError) as error:
        raise ImageOutputError(f"invalid workspace target: {error}") from error


def verify_parent_identity(parent: ParentIdentity) -> None:
    """Fail closed if the captured output parent was replaced or redirected."""
    try:
        if parent.path.is_symlink():
            raise ImageOutputError(
                f"parent directory identity changed: {parent.path} is now a symlink"
            )
        current_real_path = parent.path.resolve(strict=True)
        current_stat = parent.path.stat()
        if (
            current_real_path != parent.real_path
            or current_stat.st_dev != parent.device
            or current_stat.st_ino != parent.inode
            or not stat.S_ISDIR(current_stat.st_mode)
        ):
            raise ImageOutputError(
                f"parent directory identity changed: {parent.path}"
            )
    except ImageOutputError:
        raise
    except (OSError, ValueError) as error:
        raise ImageOutputError(
            f"cannot verify parent directory identity: {error}"
        ) from error


def _as_prepared_target(target: TargetValue) -> PreparedTarget:
    if isinstance(target, PreparedTarget):
        return target
    return prepare_target(Path(target))


def prepared_lock_target(
    target: PreparedTarget,
    basename: Optional[str] = None,
) -> Path:
    """Build a stable lock key from a captured real parent directory."""
    name = target.name if basename is None else basename
    if not isinstance(name, str) or not name or Path(name).name != name:
        raise ImageOutputError("invalid output lock basename")
    return target.parent.real_path / name


def preflight_output(
    out_path: TargetValue,
    overwrite: bool = False,
) -> PreparedTarget:
    if not isinstance(overwrite, bool):
        raise ImageOutputError("overwrite must be a boolean")

    probe_path = None
    try:
        prepared = _as_prepared_target(out_path)
        target = prepared.path
        verify_parent_identity(prepared.parent)
        if os.path.lexists(target):
            mode = target.lstat().st_mode
            if not stat.S_ISREG(mode):
                raise ImageOutputError(
                    "output path exists and is not a regular file"
                )
            if not overwrite:
                raise ImageOutputError(
                    f"output already exists; refusing to overwrite: {target}"
                )
        descriptor, probe_path = tempfile.mkstemp(
            prefix=".write-test.", dir=str(prepared.parent.path)
        )
        os.close(descriptor)
        verify_parent_identity(prepared.parent)
        os.unlink(probe_path)
        probe_path = None
    except ImageOutputError:
        raise
    except (OSError, ValueError) as error:
        raise ImageOutputError(f"output path is not writable: {error}") from error
    finally:
        if probe_path is not None:
            try:
                os.unlink(probe_path)
            except OSError:
                pass
    return prepared


def _open_verified_parent(prepared: PreparedTarget) -> int:
    verify_parent_identity(prepared.parent)
    flags = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0)
    flags |= getattr(os, "O_NOFOLLOW", 0)
    descriptor = None
    try:
        descriptor = os.open(str(prepared.parent.path), flags)
        current = os.fstat(descriptor)
        if (
            not stat.S_ISDIR(current.st_mode)
            or current.st_dev != prepared.parent.device
            or current.st_ino != prepared.parent.inode
        ):
            raise ImageOutputError("parent directory identity changed")
    except ImageOutputError:
        if descriptor is not None:
            try:
                os.close(descriptor)
            except OSError:
                pass
        raise
    except OSError as error:
        if descriptor is not None:
            try:
                os.close(descriptor)
            except OSError:
                pass
        raise ImageOutputError(
            f"cannot open output parent directory: {error}"
        ) from error
    return descriptor


def _verify_temporary_identity(temporary: TemporaryOutput) -> None:
    try:
        current = os.fstat(temporary.descriptor)
        parent = os.fstat(temporary.parent_fd)
        if (
            not stat.S_ISREG(current.st_mode)
            or current.st_dev != temporary.device
            or current.st_ino != temporary.inode
            or not stat.S_ISDIR(parent.st_mode)
            or parent.st_dev != temporary.parent.device
            or parent.st_ino != temporary.parent.inode
        ):
            raise ImageOutputError("output temporary file identity changed")
    except ImageOutputError:
        raise
    except OSError as error:
        raise ImageOutputError(
            f"cannot verify output temporary file identity: {error}"
        ) from error


def _verify_temporary_name(temporary: TemporaryOutput) -> None:
    try:
        current = os.stat(
            temporary.name,
            dir_fd=temporary.parent_fd,
            follow_symlinks=False,
        )
        if (
            not stat.S_ISREG(current.st_mode)
            or current.st_dev != temporary.device
            or current.st_ino != temporary.inode
        ):
            raise ImageOutputError("output temporary file identity changed")
    except ImageOutputError:
        raise
    except OSError as error:
        raise ImageOutputError(
            f"cannot verify output temporary file name: {error}"
        ) from error


def _temporary_path(target: TargetValue) -> TemporaryOutput:
    prepared = _as_prepared_target(target)
    descriptor = None
    parent_fd = None
    temporary = None
    try:
        parent_fd = _open_verified_parent(prepared)
        flags = os.O_RDWR | os.O_CREAT | os.O_EXCL
        flags |= getattr(os, "O_NOFOLLOW", 0)
        for _attempt in range(100):
            name = f".{prepared.name}.{secrets.token_hex(16)}.tmp"
            try:
                descriptor = os.open(name, flags, 0o600, dir_fd=parent_fd)
                break
            except FileExistsError:
                continue
        else:
            raise ImageOutputError("failed to allocate unique output temporary file")
        temp_stat = None
        metadata_error = None
        for _attempt in range(2):
            try:
                temp_stat = os.fstat(descriptor)
                break
            except OSError as error:
                metadata_error = error
        if temp_stat is None:
            retained_path = str(prepared.parent.path / name)
            _warn_retained_temp(
                "temporary ownership could not be established; cleanup skipped",
                retained_path,
                metadata_error,
            )
            raise ImageOutputError(
                f"cannot identify output temporary file: {metadata_error}"
            ) from metadata_error
        if not stat.S_ISREG(temp_stat.st_mode):
            raise ImageOutputError("output temporary file is not regular")
        temporary = TemporaryOutput(
            descriptor,
            parent_fd,
            name,
            temp_stat.st_dev,
            temp_stat.st_ino,
            prepared.parent,
        )
        verify_parent_identity(prepared.parent)
        return temporary
    except (ImageOutputError, OSError) as error:
        if temporary is not None:
            try:
                _remove_temp(temporary)
            except ImageOutputError:
                pass
            try:
                os.close(temporary.descriptor)
            except OSError:
                pass
        elif descriptor is not None:
            try:
                os.close(descriptor)
            except OSError:
                pass
        if parent_fd is not None:
            try:
                os.close(parent_fd)
            except OSError:
                pass
        raise ImageOutputError(f"failed to create output temporary file: {error}") from error


def _remove_temp(path: Union[str, TemporaryOutput]) -> None:
    if isinstance(path, TemporaryOutput):
        last_error = None
        for _attempt in range(2):
            try:
                _verify_temporary_identity(path)
                try:
                    current = os.stat(
                        path.name,
                        dir_fd=path.parent_fd,
                        follow_symlinks=False,
                    )
                except FileNotFoundError:
                    return
                if (
                    current.st_dev != path.device
                    or current.st_ino != path.inode
                    or not stat.S_ISREG(current.st_mode)
                ):
                    raise ImageOutputError("output temporary file identity changed")
                os.unlink(path.name, dir_fd=path.parent_fd)
                return
            except ImageOutputError:
                raise
            except OSError as error:
                last_error = error
        raise ImageOutputError(
            f"failed to remove output temporary file {path}: {last_error}"
        ) from last_error

    last_error = None
    for _attempt in range(2):
        try:
            os.unlink(path)
            return
        except FileNotFoundError:
            return
        except OSError as error:
            last_error = error
    raise ImageOutputError(
        f"failed to remove output temporary file {path}: {last_error}"
    ) from last_error


def _warn_retained_temp(context: str, path: str, error: Exception) -> None:
    try:
        print(
            f"  WARN: {context}; temporary file remains at {path}: {error}",
            file=sys.stderr,
        )
    except Exception:
        pass


def _cleanup_failed_temp(path: Union[str, TemporaryOutput]) -> None:
    try:
        _remove_temp(path)
    except ImageOutputError as error:
        _warn_retained_temp("output failed", path, error)


def _validate_temp(
    path: Union[str, TemporaryOutput],
    target: TargetValue,
    validator=validate_image_bytes,
) -> int:
    prepared = _as_prepared_target(target)
    try:
        verify_parent_identity(prepared.parent)
        if isinstance(path, TemporaryOutput):
            _verify_temporary_identity(path)
            _verify_temporary_name(path)
            os.lseek(path.descriptor, 0, os.SEEK_SET)
            with os.fdopen(os.dup(path.descriptor), "rb") as stream:
                data = read_bounded_image_stream(stream)
            _verify_temporary_identity(path)
            _verify_temporary_name(path)
        else:
            with Path(path).open("rb") as stream:
                data = read_bounded_image_stream(stream)
        loaded = validator(data, prepared)
    except ImageOutputError:
        raise
    return loaded.byte_count


def _remove_published_target(
    temporary: TemporaryOutput,
    name: str,
) -> None:
    try:
        current = os.stat(
            name,
            dir_fd=temporary.parent_fd,
            follow_symlinks=False,
        )
        if (
            current.st_dev != temporary.device
            or current.st_ino != temporary.inode
            or not stat.S_ISREG(current.st_mode)
        ):
            return
        os.unlink(name, dir_fd=temporary.parent_fd)
    except FileNotFoundError:
        return
    except OSError:
        return


def _publish_temp(
    temp_path: Union[str, TemporaryOutput],
    target: TargetValue,
    overwrite: bool,
) -> None:
    prepared = _as_prepared_target(target)
    if not isinstance(temp_path, TemporaryOutput):
        raise ImageOutputError("output temporary file is not identity-bound")
    try:
        verify_parent_identity(prepared.parent)
        _verify_temporary_identity(temp_path)
        _verify_temporary_name(temp_path)
        if overwrite:
            os.rename(
                temp_path.name,
                prepared.name,
                src_dir_fd=temp_path.parent_fd,
                dst_dir_fd=temp_path.parent_fd,
            )
        else:
            os.link(
                temp_path.name,
                prepared.name,
                src_dir_fd=temp_path.parent_fd,
                dst_dir_fd=temp_path.parent_fd,
                follow_symlinks=False,
            )
        published = os.stat(
            prepared.name,
            dir_fd=temp_path.parent_fd,
            follow_symlinks=False,
        )
        if (
            published.st_dev != temp_path.device
            or published.st_ino != temp_path.inode
            or not stat.S_ISREG(published.st_mode)
        ):
            raise ImageOutputError("published output identity changed")
        try:
            verify_parent_identity(prepared.parent)
        except ImageOutputError:
            _remove_published_target(temp_path, prepared.name)
            raise
    except FileExistsError as error:
        raise ImageOutputError(
            f"output already exists; refusing to overwrite: {prepared.path}"
        ) from error
    except OSError as error:
        raise ImageOutputError(f"failed to publish image atomically: {error}") from error

    try:
        _remove_temp(temp_path)
    except ImageOutputError as error:
        _warn_retained_temp(
            "output was published but cleanup failed", temp_path, error
        )


def _publish_image_bytes(
    data: bytes,
    target: TargetValue,
    overwrite: bool,
    validator,
) -> int:
    if not isinstance(data, bytes) or not data:
        raise ImageOutputError("image data must be non-empty bytes")
    if len(data) > MAX_IMAGE_BYTES:
        raise ImageOutputError(
            f"image data exceeds maximum size of {MAX_IMAGE_BYTES} bytes"
        )
    temporary = _temporary_path(target)
    published = False
    try:
        with os.fdopen(os.dup(temporary.descriptor), "wb") as output:
            output.write(data)
            output.flush()
            os.fsync(output.fileno())
        if validator is validate_image_bytes:
            byte_count = _validate_temp(temporary, target)
        else:
            byte_count = _validate_temp(temporary, target, validator)
        _publish_temp(temporary, target, overwrite)
        published = True
        return byte_count
    except ImageOutputError:
        raise
    except OSError as error:
        raise ImageOutputError(f"failed to write image: {error}") from error
    finally:
        if not published:
            _cleanup_failed_temp(temporary)
        try:
            os.close(temporary.descriptor)
        except OSError:
            pass
        try:
            os.close(temporary.parent_fd)
        except OSError:
            pass


def publish_bytes(data: bytes, target: TargetValue, overwrite: bool = False) -> int:
    """Publish an image only when it passes the strict shared 16:9 boundary."""
    return _publish_image_bytes(data, target, overwrite, validate_image_bytes)


def publish_decoded_image_bytes(
    data: bytes,
    target: TargetValue,
    overwrite: bool = False,
) -> int:
    """Publish bounded image bytes after format/decode validation only.

    This is for retaining an immutable raw artifact before a caller applies a
    stricter, source-specific transform. It must not be used for API outputs.
    """
    return _publish_image_bytes(
        data,
        target,
        overwrite,
        validate_decoded_image_bytes,
    )


def publish_stream(
    response,
    target: TargetValue,
    overwrite: bool = False,
    max_bytes: int = MAX_IMAGE_BYTES,
) -> int:
    headers = getattr(response, "headers", {})
    content_length = None
    try:
        content_length = headers.get("Content-Length")
    except AttributeError:
        pass
    if content_length:
        try:
            declared_length = int(content_length)
        except (TypeError, ValueError) as error:
            raise ImageOutputError("download Content-Length is invalid") from error
        if declared_length < 0 or declared_length > max_bytes:
            raise ImageOutputError(
                f"download exceeds maximum image size of {max_bytes} bytes"
            )

    temporary = _temporary_path(target)
    published = False
    try:
        byte_count = 0
        with os.fdopen(os.dup(temporary.descriptor), "wb") as output:
            while True:
                try:
                    chunk = response.read(64 * 1024)
                except (OSError, http.client.HTTPException) as error:
                    raise ImageStreamError(f"image download failed: {error}") from error
                if not chunk:
                    break
                if not isinstance(chunk, bytes):
                    raise ImageOutputError("download returned non-byte image data")
                byte_count += len(chunk)
                if byte_count > max_bytes:
                    raise ImageOutputError(
                        f"download exceeds maximum image size of {max_bytes} bytes"
                    )
                output.write(chunk)
            output.flush()
            os.fsync(output.fileno())
        byte_count = _validate_temp(temporary, target)
        _publish_temp(temporary, target, overwrite)
        published = True
        return byte_count
    except ImageOutputError:
        raise
    except OSError as error:
        raise ImageOutputError(f"failed to download image: {error}") from error
    finally:
        if not published:
            _cleanup_failed_temp(temporary)
        try:
            os.close(temporary.descriptor)
        except OSError:
            pass
        try:
            os.close(temporary.parent_fd)
        except OSError:
            pass
