"""Shared validation and atomic publication for generated slide images."""

import base64
import binascii
import http.client
import io
import json
import os
import stat
import sys
import tempfile
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import NamedTuple, Optional, Union

from PIL import Image, UnidentifiedImageError

OUTPUT_FORMATS = {
    ".jpg": "jpeg",
    ".jpeg": "jpeg",
    ".png": "png",
    ".webp": "webp",
}
PIL_FORMATS = {
    "jpeg": "JPEG",
    "png": "PNG",
    "webp": "WEBP",
}
MIME_TYPES = {
    "jpeg": "image/jpeg",
    "png": "image/png",
    "webp": "image/webp",
}
MAX_IMAGE_BYTES = 50 * 1024 * 1024
MAX_IMAGE_PIXELS = 64_000_000
MAX_ENCODED_IMAGE_BYTES = 4 * ((MAX_IMAGE_BYTES + 2) // 3)
MAX_PROVIDER_RESPONSE_BYTES = MAX_ENCODED_IMAGE_BYTES + 1024 * 1024
PROVIDER_RESPONSE_READ_CHUNK_BYTES = 64 * 1024
MAX_PROVIDER_RESPONSE_READS = 4096
MAX_RETRIES = 10
MAX_JSON_NESTING = 100
MAX_JSON_NODES = 100_000
MAX_JSON_CONTAINER_ITEMS = 10_000


class ImageOutputError(ValueError):
    """Raised when generated bytes cannot safely become the requested output."""


class ImageStreamError(ImageOutputError):
    """Raised for a retryable transport failure while reading image bytes."""


class LoadedImage(NamedTuple):
    image: Optional[Image.Image]
    image_format: str
    byte_count: int
    width: int
    height: int


@dataclass(frozen=True)
class ParentIdentity:
    path: Path
    real_path: Path
    device: int
    inode: int


@dataclass(frozen=True)
class PreparedTarget:
    path: Path
    parent: ParentIdentity

    def __fspath__(self) -> str:
        return str(self.path)

    def __str__(self) -> str:
        return str(self.path)

    @property
    def suffix(self) -> str:
        return self.path.suffix

    @property
    def name(self) -> str:
        return self.path.name


TargetValue = Union[Path, PreparedTarget]


def validate_retries(retries: object) -> int:
    if (
        isinstance(retries, bool)
        or not isinstance(retries, int)
        or retries < 0
        or retries > MAX_RETRIES
    ):
        raise ImageOutputError(
            f"retries must be a non-boolean integer >= 0 and at most {MAX_RETRIES}"
        )
    return retries


def parse_json_response(raw_response: object) -> object:
    """Parse bounded provider JSON without leaking decoder recursion failures."""
    try:
        parsed = json.loads(raw_response)
    except (TypeError, ValueError, UnicodeError, RecursionError) as error:
        raise ImageOutputError("provider response is not valid JSON") from error

    # CPython's JSON decoder recursion behavior differs by version. Enforce
    # deterministic resource limits with one iterator frame per active level;
    # never allocate one pending traversal tuple per sibling.
    stack = []
    value = parsed
    depth = 0
    node_count = 0
    while True:
        node_count += 1
        if node_count > MAX_JSON_NODES:
            raise ImageOutputError("provider response is not valid JSON")

        if isinstance(value, (dict, list)):
            if depth > MAX_JSON_NESTING or len(value) > MAX_JSON_CONTAINER_ITEMS:
                raise ImageOutputError("provider response is not valid JSON")
            children = value.values() if isinstance(value, dict) else value
            stack.append((iter(children), depth + 1))

        while stack:
            children, child_depth = stack[-1]
            try:
                value = next(children)
            except StopIteration:
                stack.pop()
                continue
            depth = child_depth
            break
        else:
            return parsed


def output_format(out_path: str) -> str:
    extension = Path(out_path).suffix.lower()
    try:
        return OUTPUT_FORMATS[extension]
    except KeyError as error:
        supported = ", ".join(sorted(OUTPUT_FORMATS))
        raise ImageOutputError(
            f"Unsupported output extension '{extension or '<none>'}'. Use: {supported}"
        ) from error


def expected_mime_type(out_path: str) -> str:
    return MIME_TYPES[output_format(out_path)]


def capture_path_base() -> Path:
    """Capture one absolute CWD for resolving every path in a public call."""
    try:
        return Path.cwd()
    except (OSError, ValueError, RuntimeError) as error:
        raise ImageOutputError(
            f"cannot capture current working directory: {error}"
        ) from error


def _absolute_path(value: object, base: Optional[Path]) -> Path:
    expanded = Path(value).expanduser()
    path_base = capture_path_base() if base is None else Path(base)
    if not path_base.is_absolute():
        raise ValueError("path base must be absolute")
    combined = expanded if expanded.is_absolute() else path_base / expanded
    absolute = Path(os.path.abspath(str(combined)))
    if "\0" in str(absolute):
        raise ValueError("embedded null byte")
    return absolute


def resolve_output_path(target: object, base: Optional[Path] = None) -> Path:
    """Freeze output ancestors as a real absolute path without following basename."""
    try:
        absolute = _absolute_path(target, base)
        return absolute.parent.resolve(strict=False) / absolute.name
    except (TypeError, ValueError, OSError, RuntimeError) as error:
        raise ImageOutputError(f"invalid output target: {error}") from error


def resolve_input_path(source: object, base: Optional[Path] = None) -> Path:
    """Freeze an input path, following its current final symlink referent."""
    try:
        return _absolute_path(source, base).resolve(strict=False)
    except (TypeError, ValueError, OSError, RuntimeError) as error:
        raise ImageOutputError(f"invalid input path: {error}") from error


def decode_base64(encoded: object) -> bytes:
    if not isinstance(encoded, str) or not encoded:
        raise ImageOutputError("image Base64 must be a non-empty string")
    max_encoded_bytes = 4 * ((MAX_IMAGE_BYTES + 2) // 3)
    if len(encoded) > max_encoded_bytes:
        raise ImageOutputError(
            f"image Base64 exceeds maximum encoded size of {max_encoded_bytes} bytes"
        )
    try:
        decoded = base64.b64decode(encoded, validate=True)
    except (binascii.Error, UnicodeError, ValueError) as error:
        raise ImageOutputError("image Base64 is invalid") from error
    if not decoded:
        raise ImageOutputError("image data is empty")
    if len(decoded) > MAX_IMAGE_BYTES:
        raise ImageOutputError(
            f"image data exceeds maximum size of {MAX_IMAGE_BYTES} bytes"
        )
    return decoded


def read_response_body(response) -> bytes:
    """Read one provider response with a hard maximum allocation boundary."""
    data = bytearray()
    remaining = MAX_PROVIDER_RESPONSE_BYTES + 1
    read_count = 0
    while remaining:
        if read_count >= MAX_PROVIDER_RESPONSE_READS:
            raise ImageOutputError("provider response returned too many chunks")
        read_count += 1
        try:
            chunk = response.read(
                min(PROVIDER_RESPONSE_READ_CHUNK_BYTES, remaining)
            )
        except TypeError as error:
            raise ImageOutputError(
                "provider response does not support bounded reads"
            ) from error
        except (OSError, http.client.HTTPException) as error:
            raise ImageStreamError(
                f"provider response read failed: {error}"
            ) from error
        if not isinstance(chunk, bytes):
            raise ImageOutputError("provider response body must be bytes")
        if not chunk:
            break
        data.extend(chunk[:remaining])
        remaining -= min(len(chunk), remaining)

    if len(data) > MAX_PROVIDER_RESPONSE_BYTES:
        raise ImageOutputError(
            "provider response exceeds maximum size of "
            f"{MAX_PROVIDER_RESPONSE_BYTES} bytes"
        )
    return bytes(data)


def _validate_dimensions(width: int, height: int) -> None:
    if width <= 0 or height <= 0:
        raise ImageOutputError("image dimensions must be positive")
    if width * height > MAX_IMAGE_PIXELS:
        raise ImageOutputError(
            "image dimensions are too large; maximum pixel count is "
            f"{MAX_IMAGE_PIXELS}"
        )


def load_image(
    path: Path,
    verify: bool = False,
    copy_image: bool = True,
) -> LoadedImage:
    """Load one image under shared byte, pixel, and Pillow bomb limits."""
    image_path = Path(path)
    try:
        stated_size = image_path.stat().st_size
        if stated_size <= 0:
            raise ImageOutputError("image data is empty")
        if stated_size > MAX_IMAGE_BYTES:
            raise ImageOutputError(
                f"image exceeds maximum size of {MAX_IMAGE_BYTES} bytes"
            )
        with image_path.open("rb") as source:
            data = source.read(MAX_IMAGE_BYTES + 1)
        byte_count = len(data)
        if byte_count > MAX_IMAGE_BYTES:
            raise ImageOutputError(
                f"image exceeds maximum size of {MAX_IMAGE_BYTES} bytes"
            )

        with warnings.catch_warnings():
            warnings.simplefilter("error", Image.DecompressionBombWarning)
            if verify:
                with Image.open(io.BytesIO(data)) as image:
                    _validate_dimensions(*image.size)
                    image.verify()
            with Image.open(io.BytesIO(data)) as image:
                width, height = image.size
                _validate_dimensions(width, height)
                image_format = image.format
                image.load()
                loaded = image.copy() if copy_image else None
    except ImageOutputError:
        raise
    except (Image.DecompressionBombError, Image.DecompressionBombWarning) as error:
        raise ImageOutputError(f"image dimensions are too large: {error}") from error
    except (OSError, SyntaxError, ValueError, UnidentifiedImageError) as error:
        raise ImageOutputError(f"data is not a valid image: {error}") from error

    return LoadedImage(loaded, image_format, byte_count, width, height)


def prepare_target(target: Path) -> PreparedTarget:
    """Capture the parent directory identity for one output target."""
    try:
        output_path = Path(os.path.abspath(str(Path(target).expanduser())))
    except (TypeError, ValueError, OSError) as error:
        raise ImageOutputError(f"invalid output target: {error}") from error
    parent_path = output_path.parent
    try:
        parent_path.mkdir(parents=True, exist_ok=True)
        if parent_path.is_symlink():
            raise ImageOutputError(
                f"parent directory identity is unsafe: {parent_path} is a symlink"
            )
        real_path = parent_path.resolve(strict=True)
        parent_stat = parent_path.stat()
        if not stat.S_ISDIR(parent_stat.st_mode):
            raise ImageOutputError(
                f"parent directory identity is unsafe: {parent_path} is not a directory"
            )
    except ImageOutputError:
        raise
    except (OSError, ValueError) as error:
        raise ImageOutputError(
            f"cannot capture parent directory identity: {error}"
        ) from error
    return PreparedTarget(
        output_path,
        ParentIdentity(
            parent_path,
            real_path,
            parent_stat.st_dev,
            parent_stat.st_ino,
        ),
    )


def verify_parent_identity(parent: ParentIdentity) -> None:
    """Fail closed if the captured output parent was replaced or redirected."""
    try:
        if parent.path.is_symlink():
            raise ImageOutputError(
                f"parent directory identity changed: {parent.path} is now a symlink"
            )
        current_real_path = parent.path.resolve(strict=True)
        current_stat = parent.path.stat()
        if (
            current_real_path != parent.real_path
            or current_stat.st_dev != parent.device
            or current_stat.st_ino != parent.inode
            or not stat.S_ISDIR(current_stat.st_mode)
        ):
            raise ImageOutputError(
                f"parent directory identity changed: {parent.path}"
            )
    except ImageOutputError:
        raise
    except (OSError, ValueError) as error:
        raise ImageOutputError(
            f"cannot verify parent directory identity: {error}"
        ) from error


def _as_prepared_target(target: TargetValue) -> PreparedTarget:
    if isinstance(target, PreparedTarget):
        return target
    return prepare_target(Path(target))


def prepared_lock_target(
    target: PreparedTarget,
    basename: Optional[str] = None,
) -> Path:
    """Build a stable lock key from a captured real parent directory."""
    name = target.name if basename is None else basename
    if not isinstance(name, str) or not name or Path(name).name != name:
        raise ImageOutputError("invalid output lock basename")
    return target.parent.real_path / name


def preflight_output(
    out_path: TargetValue,
    overwrite: bool = False,
) -> PreparedTarget:
    if not isinstance(overwrite, bool):
        raise ImageOutputError("overwrite must be a boolean")

    probe_path = None
    try:
        prepared = _as_prepared_target(out_path)
        target = prepared.path
        verify_parent_identity(prepared.parent)
        if os.path.lexists(target):
            if not overwrite:
                raise ImageOutputError(
                    f"output already exists; refusing to overwrite: {target}"
                )
            mode = target.lstat().st_mode
            if not stat.S_ISREG(mode):
                raise ImageOutputError(
                    "output path exists and is not a regular file"
                )
        descriptor, probe_path = tempfile.mkstemp(
            prefix=".write-test.", dir=str(prepared.parent.path)
        )
        os.close(descriptor)
        verify_parent_identity(prepared.parent)
        os.unlink(probe_path)
        probe_path = None
    except ImageOutputError:
        raise
    except (OSError, ValueError) as error:
        raise ImageOutputError(f"output path is not writable: {error}") from error
    finally:
        if probe_path is not None:
            try:
                os.unlink(probe_path)
            except OSError:
                pass
    return prepared


def _temporary_path(target: TargetValue):
    prepared = _as_prepared_target(target)
    descriptor = None
    temp_path = None
    try:
        verify_parent_identity(prepared.parent)
        result = tempfile.mkstemp(
            prefix=f".{prepared.name}.",
            suffix=".tmp",
            dir=str(prepared.parent.path),
        )
        descriptor = result[0]
        temp_path = result[1]
        verify_parent_identity(prepared.parent)
        return result
    except (ImageOutputError, OSError) as error:
        if descriptor is not None:
            try:
                os.close(descriptor)
            except OSError:
                pass
        if temp_path is not None:
            try:
                os.unlink(temp_path)
            except OSError:
                pass
        raise ImageOutputError(f"failed to create output temporary file: {error}") from error


def _remove_temp(path: str) -> None:
    last_error = None
    for _attempt in range(2):
        try:
            os.unlink(path)
            return
        except FileNotFoundError:
            return
        except OSError as error:
            last_error = error
    raise ImageOutputError(
        f"failed to remove output temporary file {path}: {last_error}"
    ) from last_error


def _warn_retained_temp(context: str, path: str, error: Exception) -> None:
    try:
        print(
            f"  WARN: {context}; temporary file remains at {path}: {error}",
            file=sys.stderr,
        )
    except Exception:
        pass


def _cleanup_failed_temp(path: str) -> None:
    try:
        _remove_temp(path)
    except ImageOutputError as error:
        _warn_retained_temp("output failed", path, error)


def _validate_temp(path: str, target: TargetValue) -> int:
    prepared = _as_prepared_target(target)
    try:
        verify_parent_identity(prepared.parent)
        loaded = load_image(Path(path), verify=True, copy_image=False)
        width, height = loaded.width, loaded.height
        actual_format = loaded.image_format
    except ImageOutputError:
        raise

    expected_format = PIL_FORMATS[output_format(str(prepared))]
    if actual_format != expected_format:
        raise ImageOutputError(
            f"image format {actual_format or '<unknown>'} does not match "
            f"{prepared.suffix.lower()}"
        )
    if width <= 0 or height <= 0 or width * 9 != height * 16:
        raise ImageOutputError(
            f"generated image must be exactly 16:9; received {width}x{height}"
        )
    return loaded.byte_count


def _publish_temp(temp_path: str, target: TargetValue, overwrite: bool) -> None:
    prepared = _as_prepared_target(target)
    try:
        verify_parent_identity(prepared.parent)
        if overwrite:
            os.replace(temp_path, prepared.path)
            return
        os.link(temp_path, prepared.path)
    except FileExistsError as error:
        raise ImageOutputError(
            f"output already exists; refusing to overwrite: {prepared.path}"
        ) from error
    except OSError as error:
        raise ImageOutputError(f"failed to publish image atomically: {error}") from error

    try:
        _remove_temp(temp_path)
    except ImageOutputError as error:
        _warn_retained_temp(
            "output was published but cleanup failed", temp_path, error
        )


def publish_bytes(data: bytes, target: TargetValue, overwrite: bool = False) -> int:
    if not isinstance(data, bytes) or not data:
        raise ImageOutputError("image data must be non-empty bytes")
    if len(data) > MAX_IMAGE_BYTES:
        raise ImageOutputError(
            f"image data exceeds maximum size of {MAX_IMAGE_BYTES} bytes"
        )
    descriptor, temp_path = _temporary_path(target)
    published = False
    try:
        with os.fdopen(descriptor, "wb") as output:
            output.write(data)
            output.flush()
            os.fsync(output.fileno())
        byte_count = _validate_temp(temp_path, target)
        _publish_temp(temp_path, target, overwrite)
        published = True
        return byte_count
    except ImageOutputError:
        raise
    except OSError as error:
        raise ImageOutputError(f"failed to write image: {error}") from error
    finally:
        if not published and os.path.lexists(temp_path):
            _cleanup_failed_temp(temp_path)


def publish_stream(
    response,
    target: TargetValue,
    overwrite: bool = False,
    max_bytes: int = MAX_IMAGE_BYTES,
) -> int:
    headers = getattr(response, "headers", {})
    content_length = None
    try:
        content_length = headers.get("Content-Length")
    except AttributeError:
        pass
    if content_length:
        try:
            declared_length = int(content_length)
        except (TypeError, ValueError) as error:
            raise ImageOutputError("download Content-Length is invalid") from error
        if declared_length < 0 or declared_length > max_bytes:
            raise ImageOutputError(
                f"download exceeds maximum image size of {max_bytes} bytes"
            )

    descriptor, temp_path = _temporary_path(target)
    published = False
    try:
        byte_count = 0
        with os.fdopen(descriptor, "wb") as output:
            while True:
                try:
                    chunk = response.read(64 * 1024)
                except (OSError, http.client.HTTPException) as error:
                    raise ImageStreamError(f"image download failed: {error}") from error
                if not chunk:
                    break
                if not isinstance(chunk, bytes):
                    raise ImageOutputError("download returned non-byte image data")
                byte_count += len(chunk)
                if byte_count > max_bytes:
                    raise ImageOutputError(
                        f"download exceeds maximum image size of {max_bytes} bytes"
                    )
                output.write(chunk)
            output.flush()
            os.fsync(output.fileno())
        byte_count = _validate_temp(temp_path, target)
        _publish_temp(temp_path, target, overwrite)
        published = True
        return byte_count
    except ImageOutputError:
        raise
    except OSError as error:
        raise ImageOutputError(f"failed to download image: {error}") from error
    finally:
        if not published and os.path.lexists(temp_path):
            _cleanup_failed_temp(temp_path)
